### ISSUE TITLE
3.2.5 cannot compile POW

### ISSUE THREAD

**Issue by Reinhartd** [arendst/Sonoff-MQTT-OTA-Arduino#255]
when i set POW in Version 3.2.5 i cannot compile with arduino IDE 1.8.1!

`exit status 1
'WS2812_LEDS' was not declared in this scope`
here is the Error message

when i set to "Sonoff" then the Compiler is running error free!

LG

**Comment by arendst** [comment]
Fixed in 3.2.6 just released

**Comment by Reinhartd** [comment]
Thank You very much!
