### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by zschramm** [arendst/Sonoff-MQTT-OTA-Arduino#149]
Sorry if this is a dumb question, but I cloned the folders and updated user_config.h and when I compile with settings as described, I get:

`'addLog_P'` was not declared in this scope``

Typically this means a missing semi-colon or brace not closed, or library reference?  I downloaded the code directly so I would assume it was working?   These little things always seem to get me. 

I also get all these other errors during compile:
D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void CFG_Default()':

sonoff:405: error: 'addLog_P' was not declared in this scope

   addLog_P(LOG_LEVEL_NONE, PSTR("Config: Use default configuration"));

                                                                     ^

sonoff:424: error: 'STA_SSID2' was not declared in this scope

   strlcpy(sysCfg.sta_ssid[1], STA_SSID2, sizeof(sysCfg.sta_ssid[1]));

                               ^

sonoff:425: error: 'STA_PASS2' was not declared in this scope

   strlcpy(sysCfg.sta_pwd[1], STA_PASS2, sizeof(sysCfg.sta_pwd[1]));

                              ^

sonoff:488: error: 'CFG_Save' was not declared in this scope

   CFG_Save();

            ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void CFG_Migrate_Part2()':

sonoff:493: error: 'addLog_P' was not declared in this scope

   addLog_P(LOG_LEVEL_NONE, PSTR("Config: Migrating configuration"));

                                                                   ^

sonoff:577: error: 'CFG_Save' was not declared in this scope

   CFG_Save();

            ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void mqtt_publish(const char*, const char*, boolean)':

sonoff:723: error: 'addLog' was not declared in this scope

   addLog(LOG_LEVEL_INFO, log);

                             ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void mqtt_connected()':

sonoff:811: error: 'spiffsPresent' was not declared in this scope

     if (!spiffsPresent()) {

                        ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void mqtt_reconnect()':

sonoff:851: error: 'mqttDataCb' was not declared in this scope

     mqttClient.setCallback(mqttDataCb);

                            ^

sonoff:857: error: 'addLog_P' was not declared in this scope

   addLog_P(LOG_LEVEL_INFO, PSTR("MQTT: Attempting connection..."));

                                                                  ^

sonoff:872: error: 'addLog' was not declared in this scope

     addLog(LOG_LEVEL_DEBUG, log);

                                ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void mqttDataCb(char*, byte*, unsigned int)':

sonoff:890: error: 'addLog' was not declared in this scope

   addLog(LOG_LEVEL_DEBUG_MORE, svalue);

                                      ^

sonoff:987: error: 'do_cmnd_power' was not declared in this scope

       do_cmnd_power(index, payload);

                                   ^

sonoff:1095: error: 'rtc_time' was not declared in this scope

             rtc_time(0).c_str(), rtc_time(1).c_str(), rtc_time(2).c_str(), rtc_time(3).c_str());

                       ^

sonoff:1098: error: 'rtc_time' was not declared in this scope

             rtc_time(0).c_str(), rtc_time(1).c_str(), rtc_time(2).c_str(), rtc_time(3).c_str());

                       ^

sonoff:1115: error: 'CFG_Save' was not declared in this scope

       CFG_Save();

                ^

sonoff:1195: error: 'STA_SSID2' was not declared in this scope

         strlcpy(sysCfg.sta_ssid[index -1], (payload == 1) ? (index == 1) ? STA_SSID1 : STA_SSID2 : dataBuf, sizeof(sysCfg.sta_ssid[0]));

                                                                                        ^

sonoff:1203: error: 'STA_PASS2' was not declared in this scope

         strlcpy(sysCfg.sta_pwd[index -1], (payload == 1) ? (index == 1) ? STA_PASS1 : STA_PASS2 : dataBuf, sizeof(sysCfg.sta_pwd[0]));

                                                                                       ^

sonoff:1224: error: 'WIFI_State' was not declared in this scope

         if (WIFI_State() != WIFI_RESTART) {

                        ^

sonoff:1387: error: 'send_button_power' was not declared in this scope

             send_button_power(i, 3);  // Clear MQTT retain in broker

                                   ^

sonoff:1417: error: 'addLog_P' was not declared in this scope

         addLog_P(LOG_LEVEL_INFO, PSTR("APP: Restarting"));

                                                         ^

sonoff:1452: error: 'CFG_Dump' was not declared in this scope

       CFG_Dump();

                ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void every_second()':

sonoff:1893: error: 'addLog_P' was not declared in this scope

         addLog_P(LOG_LEVEL_INFO, PSTR("SYSL: Syslog logging re-enabled"));  // Might trigger disable again (on purpose)

                                                                         ^

sonoff:1959: error: 'WIFI_getRSSIasQuality' was not declared in this scope

           svalue, sysCfg.sta_active +1, sysCfg.sta_ssid[sysCfg.sta_active], WIFI_getRSSIasQuality(WiFi.RSSI()));

                                                                                                              ^

sonoff:1986: error: 'WIFI_getRSSIasQuality' was not declared in this scope

         snprintf_P(svalue, sizeof(svalue), PSTR("%d%s"), WIFI_getRSSIasQuality(WiFi.RSSI()), (sysCfg.mqtt_units) ? " %" : "");

                                                                                           ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void stateloop()':

sonoff:2196: error: 'addLog' was not declared in this scope

       addLog(LOG_LEVEL_DEBUG, log);

                                  ^

sonoff:2209: error: 'addLog' was not declared in this scope

     addLog(LOG_LEVEL_DEBUG, log);

                                ^

sonoff:2237: error: 'WIFI_State' was not declared in this scope

           if (WIFI_State()) {  // WPSconfig, Smartconfig or Wifimanager active

                          ^

sonoff:2321: error: 'class ESP8266HTTPUpdate' has no member named 'rebootOnUpdate'

         ESPhttpUpdate.rebootOnUpdate(false);

                       ^

sonoff:2331: error: 'class ESP8266HTTPUpdate' has no member named 'getLastErrorString'

           snprintf_P(svalue, sizeof(svalue), PSTR("Failed %s"), ESPhttpUpdate.getLastErrorString().c_str());

                                                                               ^

sonoff:2344: error: 'CFG_Save' was not declared in this scope

         CFG_Save();

                  ^

sonoff:2354: error: 'CFG_Erase' was not declared in this scope

         CFG_Erase();

                   ^

sonoff:2364: error: 'CFG_Save' was not declared in this scope

       CFG_Save();

                ^

sonoff:2367: error: 'addLog_P' was not declared in this scope

         addLog_P(LOG_LEVEL_INFO, PSTR("APP: Restarting"));

                                                         ^

sonoff:2373: error: 'WIFI_Check' was not declared in this scope

     WIFI_Check(wificheckflag);

                             ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void serial()':

sonoff:2428: error: 'addLog' was not declared in this scope

       addLog(LOG_LEVEL_INFO, log);

                                 ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void setup()':

sonoff:2455: error: 'spiffsPresent' was not declared in this scope

   if (!spiffsPresent())

                      ^

sonoff:2456: error: 'addLog_P' was not declared in this scope

     addLog_P(LOG_LEVEL_ERROR, PSTR("SPIFFS: ERROR - No spiffs present. Please reflash with at least 16K SPIFFS"));

                                                                                                                 ^

sonoff:2460: error: 'CFG_Load' was not declared in this scope

   CFG_Load();

            ^

sonoff:2477: error: 'class HardwareSerial' has no member named 'baudRate'

   if (Serial.baudRate() != Baudrate) {

              ^

sonoff:2479: error: 'addLog' was not declared in this scope

     addLog(LOG_LEVEL_INFO, log);

                               ^

sonoff:2489: error: 'addLog' was not declared in this scope

   addLog(LOG_LEVEL_DEBUG, log);

                              ^

sonoff:2500: error: 'WIFI_Connect' was not declared in this scope

   WIFI_Connect(Hostname);

                        ^

sonoff:2536: error: 'rtc_init' was not declared in this scope

   rtc_init(every_second_cb);

                           ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\sonoff.ino: In function 'void loop()':

sonoff:2546: error: 'pollDnsWeb' was not declared in this scope

   pollDnsWeb();

              ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void CFG_Save()':

support:95: error: 'addLog' was not declared in this scope

       addLog(LOG_LEVEL_DEBUG, log);

                                  ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void CFG_Load()':

support:132: error: 'addLog' was not declared in this scope

       addLog(LOG_LEVEL_DEBUG, log);

                                  ^

support:139: error: 'CFG_Migrate' was not declared in this scope

       CFG_Migrate();  // Config may be present with versions below 3.0.0

                   ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void CFG_Migrate()':

support:178: error: 'addLog' was not declared in this scope

       addLog(LOG_LEVEL_DEBUG, log);

                                  ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void CFG_Erase()':

support:201: error: 'addLog' was not declared in this scope

   addLog(LOG_LEVEL_DEBUG, log);

                              ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void CFG_Dump()':

support:245: error: 'addLog' was not declared in this scope

       addLog(LOG_LEVEL_INFO, log);

                                 ^

support:260: error: 'addLog' was not declared in this scope

       addLog(LOG_LEVEL_INFO, log);

                                 ^

support:263: error: 'addLog_P' was not declared in this scope

     addLog_P(LOG_LEVEL_ERROR, PSTR("Config: ERROR - No SPIFFS present"));

                                                                        ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void WIFI_wps_status_cb(wps_cb_status)':

support:354: error: 'addLog' was not declared in this scope

     addLog(LOG_LEVEL_DEBUG, log);

                                ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void WIFI_config(uint8_t)':

support:388: error: 'addLog_P' was not declared in this scope

       addLog_P(LOG_LEVEL_INFO, PSTR("Smartconfig: Active for 1 minute"));

                                                                        ^

support:393: error: 'addLog_P' was not declared in this scope

         addLog_P(LOG_LEVEL_INFO, PSTR("WPSconfig: Active for 1 minute"));

                                                                        ^

support:395: error: 'addLog_P' was not declared in this scope

         addLog_P(LOG_LEVEL_INFO, PSTR("WPSconfig: Failed to start"));

                                                                    ^

support:401: error: 'addLog_P' was not declared in this scope

       addLog_P(LOG_LEVEL_INFO, PSTR("Wifimanager: Active for 1 minute"));

                                                                        ^

support:402: error: 'beginWifiManager' was not declared in this scope

       beginWifiManager();

                        ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void WIFI_begin(uint8_t)':

support:415: error: 'addLog_P' was not declared in this scope

     addLog_P(LOG_LEVEL_DEBUG, "Wifi: Patch issue 2186");

                                                       ^

support:421: error: 'class ESP8266WiFiClass' has no member named 'getAutoConnect'

   if (!WiFi.getAutoConnect()) WiFi.setAutoConnect(true);

             ^

support:421: error: 'class ESP8266WiFiClass' has no member named 'setAutoConnect'

   if (!WiFi.getAutoConnect()) WiFi.setAutoConnect(true);

                                    ^

support:434: error: 'class ESP8266WiFiClass' has no member named 'getPhyMode'

     sysCfg.sta_active +1, sysCfg.sta_ssid[sysCfg.sta_active], sysCfg.sta_pwd[sysCfg.sta_active], PhyMode[WiFi.getPhyMode() & 0x3], Hostname);

                                                                                                               ^

support:435: error: 'addLog' was not declared in this scope

   addLog(LOG_LEVEL_INFO, log);

                             ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void WIFI_check_ip()':

support:443: error: 'addLog_P' was not declared in this scope

     addLog_P((_wifistatus != WL_CONNECTED) ? LOG_LEVEL_INFO : LOG_LEVEL_DEBUG_MORE, PSTR("Wifi: Connected"));

                                                                                                            ^

support:449: error: 'addLog_P' was not declared in this scope

         addLog_P(LOG_LEVEL_INFO, PSTR("Wifi: Connect failed as no IP address received"));

                                                                                        ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void WIFI_Check(uint8_t)':

support:506: error: 'addLog' was not declared in this scope

           addLog(LOG_LEVEL_INFO, log);

                                     ^

support:515: error: 'addLog_P' was not declared in this scope

         addLog_P(LOG_LEVEL_DEBUG_MORE, PSTR("Wifi: Checking connection..."));

                                                                            ^

support:522: error: 'startWebserver' was not declared in this scope

           startWebserver(sysCfg.webserver, WiFi.localIP());

                                                          ^

support:524: error: 'stopWebserver' was not declared in this scope

           stopWebserver();

                         ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void rtc_second()':

support:926: error: 'addLog' was not declared in this scope

       addLog(LOG_LEVEL_DEBUG, log);

                                  ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\support.ino: In function 'void syslog(const char*)':

support:986: error: 'addLog' was not declared in this scope

     addLog(LOG_LEVEL_INFO, str);

                               ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: At global scope:

webserver:121: error: expected ',' or ';' before 'STA_SSID2'

   "<br/><b>AP2 SSId</b> (" STA_SSID2 ")<br/><input id='s2' name='s2' length=32 placeholder='" STA_SSID2 "' value='{s2}'><br/>"

                            ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void startWebserver(int, IPAddress)':

webserver:270: error: 'handleRoot' was not declared in this scope

       webServer->on("/", handleRoot);

                          ^

webserver:271: error: 'handleConfig' was not declared in this scope

       webServer->on("/cn", handleConfig);

                            ^

webserver:272: error: 'handleWifi1' was not declared in this scope

       webServer->on("/w1", handleWifi1);

                            ^

webserver:273: error: 'handleWifi0' was not declared in this scope

       webServer->on("/w0", handleWifi0);

                            ^

webserver:274: error: 'handleMqtt' was not declared in this scope

       webServer->on("/mq", handleMqtt);

                            ^

webserver:276: error: 'handleDomoticz' was not declared in this scope

       webServer->on("/dm", handleDomoticz);

                            ^

webserver:278: error: 'handleLog' was not declared in this scope

       webServer->on("/lg", handleLog);

                            ^

webserver:279: error: 'handleSave' was not declared in this scope

       webServer->on("/sv", handleSave);

                            ^

webserver:280: error: 'handleReset' was not declared in this scope

       webServer->on("/rt", handleReset);

                            ^

webserver:281: error: 'handleUpgrade' was not declared in this scope

       webServer->on("/up", handleUpgrade);

                            ^

webserver:282: error: 'handleUpgradeStart' was not declared in this scope

       webServer->on("/u1", handleUpgradeStart);

                            ^

webserver:283: error: 'handleUploadDone' was not declared in this scope

       webServer->on("/u2", HTTP_POST, handleUploadDone, handleUploadLoop);

                                       ^

webserver:283: error: 'handleUploadLoop' was not declared in this scope

       webServer->on("/u2", HTTP_POST, handleUploadDone, handleUploadLoop);

                                                         ^

webserver:284: error: 'handleConsole' was not declared in this scope

       webServer->on("/cm", handleConsole);

                            ^

webserver:285: error: 'handleAjax' was not declared in this scope

       webServer->on("/ax", handleAjax);

                            ^

webserver:286: error: 'handleInfo' was not declared in this scope

       webServer->on("/in", handleInfo);

                            ^

webserver:287: error: 'handleRestart' was not declared in this scope

       webServer->on("/rb", handleRestart);

                            ^

webserver:294: error: 'handleNotFound' was not declared in this scope

       webServer->onNotFound(handleNotFound);

                             ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void stopWebserver()':

webserver:308: error: 'class ESP8266WebServer' has no member named 'close'

     webServer->close();

                ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void handleRoot()':

webserver:364: error: 'captivePortal' was not declared in this scope

   if (captivePortal()) { // If captive portal redirect instead of displaying the page.

                     ^

webserver:369: error: 'handleWifi0' was not declared in this scope

     handleWifi0();

                 ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void handleWifi1()':

webserver:528: error: 'handleWifi' was not declared in this scope

   handleWifi(true);

                  ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void handleWifi0()':

webserver:533: error: 'handleWifi' was not declared in this scope

   handleWifi(false);

                   ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void handleSave()':

webserver:734: error: 'STA_SSID2' was not declared in this scope

     strlcpy(sysCfg.sta_ssid[1], (!strlen(webServer->arg("s2").c_str())) ? STA_SSID2 : webServer->arg("s2").c_str(), sizeof(sysCfg.sta_ssid[1]));

                                                                           ^

webserver:735: error: 'STA_PASS2' was not declared in this scope

     strlcpy(sysCfg.sta_pwd[1], (!strlen(webServer->arg("p2").c_str())) ? STA_PASS2 : webServer->arg("p2").c_str(), sizeof(sysCfg.sta_pwd[1]));

                                                                          ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void handleUploadLoop()':

webserver:956: error: 'class EspClass' has no member named 'magicFlashChipSize'

       uint32_t bin_flash_size = ESP.magicFlashChipSize((upload.buf[3] & 0xf0) >> 4);

                                     ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void handleInfo()':

webserver:1063: error: 'class EspClass' has no member named 'getCoreVersion'

   page += F("<tr><td><b>Core/SDK version</b></td><td>"); page += ESP.getCoreVersion(); page += F("/"); page += String(ESP.getSdkVersion()); page += F("</td></tr>");

                                                                      ^

webserver:1068: error: 'class EspClass' has no member named 'getResetReason'

   page += F("<tr><td><b>Reset reason</b></td><td>"); page += ESP.getResetReason(); page += F("</td></tr>");

                                                                  ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'void handleNotFound()':

webserver:1159: error: 'captivePortal' was not declared in this scope

   if (captivePortal()) { // If captive portal redirect instead of displaying the error page.

                     ^

D:\Dropbox\Documents\Arduino\Sonoff-MQTT-OTA-Arduino-master\sonoff\webserver.ino: In function 'boolean captivePortal()':

webserver:1183: error: 'isIp' was not declared in this scope

   if (!isIp(webServer->hostHeader())) {

                                    ^

Using library Ticker at version 1.0 in folder: C:\Users\Zac\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\Ticker 
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\Zac\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi 
Using library ESP8266HTTPClient at version 1.0 in folder: C:\Users\Zac\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266HTTPClient 
Using library ESP8266httpUpdate at version 1.0 in folder: C:\Users\Zac\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266httpUpdate 
Using library arduino_77356 at version 2.4 in folder: D:\Dropbox\Documents\Arduino\libraries\arduino_77356 
Using library ESP8266WebServer at version 1.0 in folder: C:\Users\Zac\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WebServer 
Using library DNSServer at version 1.1.0 in folder: C:\Users\Zac\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\DNSServer 
exit status 1
'addLog_P' was not declared in this scope

**Comment by arendst** [comment]
You might take a look in wiki at the top of this page...

**Comment by zschramm** [comment]
Thank you for that informative reply.  I did go through the wiki and I did not see anything addressing this issue.  Can you elaborate?

**Comment by arendst** [comment]
Suppose the code on github is correct. I know it's a bold statement but suppose it is true.

After reading the wiki, installing the correct environment and downloading the correct package (you might consider the releases tab) and you still receive these error messages then you might try a simple blink routine to your sonoff first.

**Comment by arendst** [comment]
Further on the previous answer I notice you are using version 2.0.0 of the esp8266 arduino code.

As you stated you read the wiki I kindly request to do it again this starting from the prerequisite page where it is stated that AT LEAST VERSION 2.3.0 is needed.

Happy upgrading.

**Comment by arendst** [comment]
Hope it's informative enough. RTFW.

**Comment by zschramm** [comment]
Yes that information was informative and I was able to flash the firmware.  I would have never figured it out in a million years that I needed to update the esp8266 library, the arduino IDE itself (it works on 1.6.18 btw).  

So thank you for your time and help on this.  I could have done without the sarcasm and just your 3rd response which solved it for me.

**Comment by tringler** [comment]
I have exactly the same compiler errors using Arduino 1.8.1 and esp8266 library 2.3.0 - I fulfilled all other requirement like putting in IRremoteESP8266, PubSubClient and NeoPixelBus into my lib folder. I also installed ArduinoJson. I would say I RTFW. Any idea to get rid of these compiler errors?
